In [17]:
import pandas as pd

In [ ]:
df = pd.read_csv('healthcare-dataset-stroke-data.csv') 
print(df.head())

      id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes
1  51676  Female  61.0             0              0          Yes
2  31112    Male  80.0             0              1          Yes
3  60182  Female  49.0             0              0          Yes
4   1665  Female  79.0             1              0          Yes

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked
1  Self-employed          Rural             202.21   NaN     never smoked
2        Private          Rural             105.92  32.5     never smoked
3        Private          Urban             171.23  34.4           smokes
4  Self-employed          Rural             174.12  24.0     never smoked

   stroke
0       1
1       1
2       1
3       1
4       1

In [ ]:
from sklearn.model_selection import train_test_split #splitting the dataset
from autogluon.tabular import TabularDataset, TabularPredictor #to handle tabular data and train models

In [ ]:
# split into train and test sets
df_train,df_test=train_test_split(df,test_size=0.33,random_state=1)
df_train.shape,df_test.shape

((3423, 12), (1687, 12))

In [ ]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [ ]:
test_data=df_test.drop(['label'],axis=1)
test_data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
4673,49833,Female,42.0,0,0,Yes,Govt_job,Rural,112.98,37.2,formerly smoked
3232,20375,Female,78.0,0,0,Yes,Private,Urban,78.29,30.1,formerly smoked
3694,39834,Male,28.0,0,0,No,Private,Urban,73.27,25.4,smokes
1070,42550,Female,81.0,0,0,Yes,Self-employed,Rural,246.34,21.1,never smoked
4163,19907,Female,52.0,0,0,Yes,Private,Rural,97.05,28.0,Unknown

In [ ]:
predictor = TabularPredictor(label='label').fit(train_data=df_train, verbosity=2, presets='best_quality')

In [ ]:
predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                          model  score_val eval_metric  pred_time_val    fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0            XGBoost_r95_BAG_L2   0.962022    accuracy       3.252537  142.807381                0.047465           2.469684            2       True        129
1           WeightedEnsemble_L3   0.962022    accuracy       3.252898  142.970056                0.000361           0.162675            3       True        134
2                XGBoost_BAG_L2   0.961729    accuracy       3.248770  142.556544                0.043698           2.218846            2       True         75
3          LightGBM_r130_BAG_L2   0.961729    accuracy       3.261580  142.353628                0.056509           2.015931            2       True         88
4       RandomForestGini_BAG_L2   0.961729    accuracy       3.296724  141.087705                0.091652           0.750008            2       True         71
5          LightGBMLarge_BAG_L2   0.961437    accuracy       3.284684  145.051600                0.079612           4.713902            2       True         77
6       RandomForest_r16_BAG_L2   0.961437    accuracy       3.289052  146.801004                0.083980           6.463307            2       True        124
7           LightGBM_r15_BAG_L2   0.961145    accuracy       3.245578  142.266143                0.040507           1.928446            2       True         98
8       RandomForest_r15_BAG_L2   0.961145    accuracy       3.285675  144.744251                0.080603           4.406554            2       True        117
9          LightGBM_r135_BAG_L2   0.961145    accuracy       3.291872  144.098445                0.086800           3.760748            2       True        118
10     RandomForest_r166_BAG_L2   0.961145    accuracy       3.293979  141.013800                0.088907           0.676103            2       True        114
11         LightGBM_r143_BAG_L2   0.961145    accuracy       3.337180  148.147183                0.132109           7.809486            2       True        102
12          XGBoost_r194_BAG_L2   0.960853    accuracy       3.253872  142.439997                0.048801           2.102300            2       True         90
13        ExtraTrees_r42_BAG_L2   0.960853    accuracy       3.290782  140.979788                0.085710           0.642091            2       True         83
14              LightGBM_BAG_L2   0.960561    accuracy       3.242504  142.426799                0.037433           2.089102            2       True         70
15           XGBoost_r89_BAG_L2   0.960561    accuracy       3.246733  142.539630                0.041661           2.201933            2       True         86
16         LightGBM_r131_BAG_L2   0.960561    accuracy       3.275415  143.327241                0.070343           2.989544            2       True         79
17     RandomForest_r195_BAG_L2   0.960561    accuracy       3.287693  144.918489                0.082621           4.580792            2       True         84
18      RandomForest_r39_BAG_L2   0.960561    accuracy       3.288031  144.778848                0.082959           4.441151            2       True         95
19         LightGBM_r121_BAG_L2   0.960561    accuracy       3.366115  151.158414                0.161043          10.820717            2       True        120
20           XGBoost_r22_BAG_L2   0.960269    accuracy       3.250810  142.122667                0.045738           1.784970            2       True        119
21     RandomForest_r127_BAG_L2   0.960269    accuracy       3.284326  145.394898                0.079254           5.057201            2       True        103
22           XGBoost_r34_BAG_L2   0.960269    accuracy       3.292394  143.579658                0.087322           3.241961            2       True        130
23       ExtraTrees_r178_BAG_L2   0.960269    accuracy       3.298414  140.882995                0.093342           0.545298            2       True        113
24       ExtraTrees_r197_BAG_L2   0.960269    accuracy       3.307085  141.251007                0.102013           0.913310            2       True        122
25         LightGBM_r161_BAG_L2   0.960269    accuracy       3.360289  149.383041                0.155218           9.045344            2       True         93
26      RandomForestEntr_BAG_L2   0.959977    accuracy       3.290548  140.969222                0.085476           0.631525            2       True         72
27       ExtraTrees_r172_BAG_L2   0.959977    accuracy       3.292583  141.015979                0.087511           0.678281            2       True         91
28           XGBoost_r31_BAG_L2   0.959684    accuracy       3.260722  142.912946                0.055651           2.575249            2       True        115
29        ExtraTreesGini_BAG_L2   0.959684    accuracy       3.287327  140.684645                0.082255           0.346948            2       True         73
30        ExtraTrees_r49_BAG_L2   0.959684    accuracy       3.310052  140.753523                0.104980           0.415826            2       True        101
31           XGBoost_r49_BAG_L2   0.959392    accuracy       3.259860  143.907965                0.054788           3.570268            2       True        110
32   NeuralNetTorch_r135_BAG_L2   0.959392    accuracy       3.408494  150.930978                0.203422          10.593281            2       True        125
33         LightGBM_r188_BAG_L1   0.958808    accuracy       0.047229    1.285943                0.047229           1.285943            1       True         19
34          WeightedEnsemble_L2   0.958808    accuracy       0.048492    1.441395                0.001263           0.155452            2       True         68
35           XGBoost_r33_BAG_L2   0.958808    accuracy       3.260687  144.738999                0.055615           4.401302            2       True         82
36       ExtraTrees_r126_BAG_L2   0.958808    accuracy       3.320607  140.728112                0.115535           0.390415            2       True        126
37            LightGBMXT_BAG_L1   0.958516    accuracy       0.039782    0.769399                0.039782           0.769399            1       True          3
38        ExtraTreesEntr_BAG_L2   0.958516    accuracy       3.289270  140.640257                0.084198           0.302560            2       True         74
39     NeuralNetTorch_r1_BAG_L2   0.958516    accuracy       3.410281  148.865840                0.205209           8.528143            2       True        132
40           XGBoost_r95_BAG_L1   0.958224    accuracy       0.034383    0.605456                0.034383           0.605456            1       True         63
41            LightGBMXT_BAG_L2   0.958224    accuracy       3.229038  141.474548                0.023966           1.136851            2       True         69
42          LightGBM_r96_BAG_L2   0.958224    accuracy       3.246457  141.558711                0.041386           1.221014            2       True         80
43           XGBoost_r98_BAG_L2   0.958224    accuracy       3.289153  145.501374                0.084081           5.163677            2       True         97
44   NeuralNetTorch_r197_BAG_L2   0.958224    accuracy       3.388129  146.167737                0.183058           5.830040            2       True        100
45    NeuralNetTorch_r76_BAG_L2   0.958224    accuracy       3.420980  146.371537                0.215908           6.033840            2       True        121
46          XGBoost_r194_BAG_L1   0.957932    accuracy       0.021655    0.837135                0.021655           0.837135            1       True         24
47         LightGBM_r188_BAG_L2   0.957932    accuracy       3.244607  142.649657                0.039535           2.311960            2       True         85
48          LightGBM_r94_BAG_L2   0.957932    accuracy       3.250537  141.590902                0.045466           1.253205            2       True        105
49    NeuralNetTorch_r31_BAG_L2   0.957932    accuracy       3.391513  147.661260                0.186441           7.323563            2       True        107
50   NeuralNetTorch_r185_BAG_L2   0.957932    accuracy       3.398789  147.548990                0.193717           7.211292            2       True        116
51    NeuralNetTorch_r30_BAG_L2   0.957932    accuracy       3.418877  149.538900                0.213805           9.201203            2       True         87
52          LightGBM_r42_BAG_L1   0.957639    accuracy       0.046716    0.662535                0.046716           0.662535            1       True         65
53          LightGBM_r30_BAG_L2   0.957639    accuracy       3.285554  143.014854                0.080483           2.677157            2       True        109
54         LightGBMLarge_BAG_L1   0.957347    accuracy       0.018270    0.886437                0.018270           0.886437            1       True         11
55               XGBoost_BAG_L1   0.957347    accuracy       0.028053    0.645278                0.028053           0.645278            1       True          9
56    NeuralNetTorch_r76_BAG_L1   0.957347    accuracy       0.043297    3.693230                0.043297           3.693230            1       True         55
57    NeuralNetTorch_r79_BAG_L1   0.957347    accuracy       0.045840    5.959536                0.045840           5.959536            1       True         12
58         LightGBM_r135_BAG_L1   0.957347    accuracy       0.046104    1.025478                0.046104           1.025478            1       True         52
59          LightGBM_r42_BAG_L2   0.957347    accuracy       3.235145  142.409205                0.030073           2.071508            2       True        131
60    NeuralNetTorch_r71_BAG_L2   0.957347    accuracy       3.381756  145.239148                0.176684           4.901451            2       True        112
61    NeuralNetTorch_r22_BAG_L2   0.957347    accuracy       3.398887  148.758328                0.193815           8.420631            2       True         81
62   NeuralNetTorch_r158_BAG_L2   0.957347    accuracy       3.410990  148.631667                0.205918           8.293970            2       True         99
63    NeuralNetTorch_r79_BAG_L2   0.957347    accuracy       3.412539  147.798765                0.207468           7.461068            2       True         78
64    NeuralNetTorch_r36_BAG_L2   0.957347    accuracy       3.420375  147.022982                0.215303           6.685285            2       True        127
65           XGBoost_r89_BAG_L1   0.957055    accuracy       0.028894    0.773139                0.028894           0.773139            1       True         20
66         LightGBM_r130_BAG_L1   0.957055    accuracy       0.035952    0.840071                0.035952           0.840071            1       True         22
67           XGBoost_r33_BAG_L1   0.957055    accuracy       0.049289    0.898568                0.049289           0.898568            1       True         16
68          LightGBM_r30_BAG_L1   0.957055    accuracy       0.082600    1.119954                0.082600           1.119954            1       True         43
69         LightGBM_r196_BAG_L2   0.957055    accuracy       3.311170  144.321765                0.106098           3.984068            2       True         94
70    NeuralNetTorch_r19_BAG_L2   0.957055    accuracy       3.382869  146.425853                0.177798           6.088155            2       True        128
71   NeuralNetTorch_r143_BAG_L2   0.957055    accuracy       3.421174  149.745973                0.216102           9.408276            2       True        106
72   NeuralNetTorch_r185_BAG_L1   0.956763    accuracy       0.035494    6.998711                0.035494           6.998711            1       True         50
73    NeuralNetTorch_r86_BAG_L2   0.956763    accuracy       3.428622  147.071441                0.223550           6.733744            2       True         89
74           XGBoost_r49_BAG_L1   0.956471    accuracy       0.024371    0.615116                0.024371           0.615116            1       True         44
75           XGBoost_r22_BAG_L1   0.956471    accuracy       0.025318    0.746665                0.025318           0.746665            1       True         53
76              LightGBM_BAG_L1   0.956471    accuracy       0.028216    0.730588                0.028216           0.730588            1       True          4
77          LightGBM_r94_BAG_L1   0.956471    accuracy       0.030139    0.818803                0.030139           0.818803            1       True         39
78      RandomForestEntr_BAG_L1   0.956471    accuracy       0.071497    0.274678                0.071497           0.274678            1       True          6
79    NeuralNetTorch_r14_BAG_L2   0.956471    accuracy       3.386438  145.917612                0.181367           5.579915            2       True         92
80          LightGBM_r15_BAG_L1   0.956179    accuracy       0.020150    0.515834                0.020150           0.515834            1       True         32
81    NeuralNetTorch_r19_BAG_L1   0.956179    accuracy       0.034032    3.848383                0.034032           3.848383            1       True         62
82           XGBoost_r31_BAG_L1   0.956179    accuracy       0.038102    0.816042                0.038102           0.816042            1       True         49
83   NeuralNetTorch_r143_BAG_L1   0.956179    accuracy       0.051269    9.045197                0.051269           9.045197            1       True         40
84         LightGBM_r143_BAG_L1   0.956179    accuracy       0.056482    1.122633                0.056482           1.122633            1       True         36
85         ExtraTrees_r4_BAG_L2   0.956179    accuracy       3.293062  140.842529                0.087990           0.504832            2       True        108
86    NeuralNetTorch_r89_BAG_L2   0.956179    accuracy       3.395070  148.536208                0.189999           8.198511            2       True        133
87    NeuralNetTorch_r14_BAG_L1   0.955887    accuracy       0.036446    4.366639                0.036446           4.366639            1       True         26
88         LightGBM_r131_BAG_L1   0.955887    accuracy       0.040383    0.856322                0.040383           0.856322            1       True         13
89           XGBoost_r34_BAG_L1   0.955887    accuracy       0.055278    0.644534                0.055278           0.644534            1       True         64
90        ExtraTrees_r42_BAG_L1   0.955887    accuracy       0.073047    0.440678                0.073047           0.440678            1       True         17
91        NeuralNetTorch_BAG_L2   0.955887    accuracy       3.390340  146.950538                0.185268           6.612841            2       True         76
92    NeuralNetTorch_r41_BAG_L2   0.955887    accuracy       3.392122  147.780082                0.187050           7.442385            2       True         96
93   NeuralNetTorch_r197_BAG_L1   0.955595    accuracy       0.036330    2.936318                0.036330           2.936318            1       True         34
94    NeuralNetTorch_r22_BAG_L1   0.955595    accuracy       0.065872    6.948403                0.065872           6.948403            1       True         15
95       ExtraTrees_r197_BAG_L1   0.955595    accuracy       0.069415    0.709848                0.069415           0.709848            1       True         56
96       ExtraTrees_r178_BAG_L1   0.955595    accuracy       0.069960    0.291605                0.069960           0.291605            1       True         47
97       ExtraTrees_r172_BAG_L1   0.955595    accuracy       0.075762    0.566621                0.075762           0.566621            1       True         25
98    NeuralNetTorch_r71_BAG_L1   0.955302    accuracy       0.036913    3.052474                0.036913           3.052474            1       True         46
99    NeuralNetTorch_r87_BAG_L2   0.955302    accuracy       3.381824  147.029887                0.176753           6.692190            2       True        111
100   NeuralNetTorch_r31_BAG_L1   0.955010    accuracy       0.035779    5.764166                0.035779           5.764166            1       True         41
101        LightGBM_r161_BAG_L1   0.955010    accuracy       0.090828    1.548208                0.090828           1.548208            1       True         27
102   NeuralNetTorch_r86_BAG_L1   0.954718    accuracy       0.039183    5.091021                0.039183           5.091021            1       True         23
103    NeuralNetTorch_r1_BAG_L1   0.954718    accuracy       0.039328    5.987918                0.039328           5.987918            1       True         66
104  NeuralNetTorch_r135_BAG_L1   0.954718    accuracy       0.043733    7.425530                0.043733           7.425530            1       True         59
105        LightGBM_r121_BAG_L1   0.954718    accuracy       0.062608    1.504894                0.062608           1.504894            1       True         54
106    RandomForest_r166_BAG_L1   0.954718    accuracy       0.068886    0.329878                0.068886           0.329878            1       True         48
107     RandomForestGini_BAG_L1   0.954718    accuracy       0.076601    0.377130                0.076601           0.377130            1       True          5
108         LightGBM_r96_BAG_L1   0.954426    accuracy       0.020986    0.816165                0.020986           0.816165            1       True         14
109     RandomForest_r15_BAG_L1   0.954426    accuracy       0.070536    0.408966                0.070536           0.408966            1       True         51
110       ExtraTrees_r49_BAG_L1   0.954426    accuracy       0.071564    0.282766                0.071564           0.282766            1       True         35
111       ExtraTreesEntr_BAG_L1   0.954426    accuracy       0.073176    0.252999                0.073176           0.252999            1       True          8
112       ExtraTreesGini_BAG_L1   0.954426    accuracy       0.074078    0.261799                0.074078           0.261799            1       True          7
113  NeuralNetTorch_r121_BAG_L2   0.954426    accuracy       3.409735  149.438016                0.204664           9.100319            2       True        123
114   NeuralNetTorch_r89_BAG_L1   0.954134    accuracy       0.035891    5.631305                0.035891           5.631305            1       True         67
115   NeuralNetTorch_r30_BAG_L1   0.954134    accuracy       0.050356    6.760906                0.050356           6.760906            1       True         21
116   NeuralNetTorch_r41_BAG_L1   0.954134    accuracy       0.051037    5.012497                0.051037           5.012497            1       True         30
117   NeuralNetTorch_r36_BAG_L1   0.953842    accuracy       0.037515    4.389579                0.037515           4.389579            1       True         61
118    RandomForest_r127_BAG_L1   0.953842    accuracy       0.064551    0.464082                0.064551           0.464082            1       True         37
119        LightGBM_r196_BAG_L1   0.953550    accuracy       0.013186    0.832991                0.013186           0.832991            1       True         28
120          XGBoost_r98_BAG_L1   0.953550    accuracy       0.017510    0.590260                0.017510           0.590260            1       True         31
121   NeuralNetTorch_r87_BAG_L1   0.953550    accuracy       0.039137    3.790103                0.039137           3.790103            1       True         45
122  NeuralNetTorch_r121_BAG_L1   0.953550    accuracy       0.041747    5.405076                0.041747           5.405076            1       True         57

/Users/donishchuk/Desktop/autogluon/venv/lib/python3.11/site-packages/autogluon/core/utils/plots.py:169: UserWarning: AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"
  warnings.warn('AutoGluon summary plots cannot be created because bokeh is not installed. To see plots, please do: "pip install bokeh==2.0.1"')

{'model_types': {'KNeighborsUnif_BAG_L1': 'StackerEnsembleModel_KNN',
  'KNeighborsDist_BAG_L1': 'StackerEnsembleModel_KNN',
  'LightGBMXT_BAG_L1': 'StackerEnsembleModel_LGB',
  'LightGBM_BAG_L1': 'StackerEnsembleModel_LGB',
  'RandomForestGini_BAG_L1': 'StackerEnsembleModel_RF',
  'RandomForestEntr_BAG_L1': 'StackerEnsembleModel_RF',
  'ExtraTreesGini_BAG_L1': 'StackerEnsembleModel_XT',
  'ExtraTreesEntr_BAG_L1': 'StackerEnsembleModel_XT',
  'XGBoost_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBMLarge_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r79_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBM_r131_BAG_L1': 'StackerEnsembleModel_LGB',
  'LightGBM_r96_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r22_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r33_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'ExtraTrees_r42_BAG_L1': 'StackerEnsembleModel_XT',
  'RandomForest_r195_BAG_L1': 'StackerEnsembleModel_RF',
  'LightGBM_r188_BAG_L1': 'StackerEnsembleModel_LGB',
  'XGBoost_r89_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_r30_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBM_r130_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r86_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r194_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'ExtraTrees_r172_BAG_L1': 'StackerEnsembleModel_XT',
  'NeuralNetTorch_r14_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBM_r161_BAG_L1': 'StackerEnsembleModel_LGB',
  'LightGBM_r196_BAG_L1': 'StackerEnsembleModel_LGB',
  'RandomForest_r39_BAG_L1': 'StackerEnsembleModel_RF',
  'NeuralNetTorch_r41_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r98_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'LightGBM_r15_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r158_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r197_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r49_BAG_L1': 'StackerEnsembleModel_XT',
  'LightGBM_r143_BAG_L1': 'StackerEnsembleModel_LGB',
  'RandomForest_r127_BAG_L1': 'StackerEnsembleModel_RF',
  'RandomForest_r34_BAG_L1': 'StackerEnsembleModel_RF',
  'LightGBM_r94_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r143_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r31_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r4_BAG_L1': 'StackerEnsembleModel_XT',
  'LightGBM_r30_BAG_L1': 'StackerEnsembleModel_LGB',
  'XGBoost_r49_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_r87_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r71_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r178_BAG_L1': 'StackerEnsembleModel_XT',
  'RandomForest_r166_BAG_L1': 'StackerEnsembleModel_RF',
  'XGBoost_r31_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_r185_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'RandomForest_r15_BAG_L1': 'StackerEnsembleModel_RF',
  'LightGBM_r135_BAG_L1': 'StackerEnsembleModel_LGB',
  'XGBoost_r22_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'LightGBM_r121_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r76_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r197_BAG_L1': 'StackerEnsembleModel_XT',
  'NeuralNetTorch_r121_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'RandomForest_r16_BAG_L1': 'StackerEnsembleModel_RF',
  'NeuralNetTorch_r135_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r126_BAG_L1': 'StackerEnsembleModel_XT',
  'NeuralNetTorch_r36_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r19_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r95_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'XGBoost_r34_BAG_L1': 'StackerEnsembleModel_XGBoost',
  'LightGBM_r42_BAG_L1': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r1_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r89_BAG_L1': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel',
  'LightGBMXT_BAG_L2': 'StackerEnsembleModel_LGB',
  'LightGBM_BAG_L2': 'StackerEnsembleModel_LGB',
  'RandomForestGini_BAG_L2': 'StackerEnsembleModel_RF',
  'RandomForestEntr_BAG_L2': 'StackerEnsembleModel_RF',
  'ExtraTreesGini_BAG_L2': 'StackerEnsembleModel_XT',
  'ExtraTreesEntr_BAG_L2': 'StackerEnsembleModel_XT',
  'XGBoost_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBMLarge_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r79_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBM_r131_BAG_L2': 'StackerEnsembleModel_LGB',
  'LightGBM_r96_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r22_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r33_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'ExtraTrees_r42_BAG_L2': 'StackerEnsembleModel_XT',
  'RandomForest_r195_BAG_L2': 'StackerEnsembleModel_RF',
  'LightGBM_r188_BAG_L2': 'StackerEnsembleModel_LGB',
  'XGBoost_r89_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_r30_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBM_r130_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r86_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r194_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'ExtraTrees_r172_BAG_L2': 'StackerEnsembleModel_XT',
  'NeuralNetTorch_r14_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'LightGBM_r161_BAG_L2': 'StackerEnsembleModel_LGB',
  'LightGBM_r196_BAG_L2': 'StackerEnsembleModel_LGB',
  'RandomForest_r39_BAG_L2': 'StackerEnsembleModel_RF',
  'NeuralNetTorch_r41_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r98_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'LightGBM_r15_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r158_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r197_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r49_BAG_L2': 'StackerEnsembleModel_XT',
  'LightGBM_r143_BAG_L2': 'StackerEnsembleModel_LGB',
  'RandomForest_r127_BAG_L2': 'StackerEnsembleModel_RF',
  'RandomForest_r34_BAG_L2': 'StackerEnsembleModel_RF',
  'LightGBM_r94_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r143_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r31_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r4_BAG_L2': 'StackerEnsembleModel_XT',
  'LightGBM_r30_BAG_L2': 'StackerEnsembleModel_LGB',
  'XGBoost_r49_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_r87_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r71_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r178_BAG_L2': 'StackerEnsembleModel_XT',
  'RandomForest_r166_BAG_L2': 'StackerEnsembleModel_RF',
  'XGBoost_r31_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'NeuralNetTorch_r185_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'RandomForest_r15_BAG_L2': 'StackerEnsembleModel_RF',
  'LightGBM_r135_BAG_L2': 'StackerEnsembleModel_LGB',
  'XGBoost_r22_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'LightGBM_r121_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r76_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r197_BAG_L2': 'StackerEnsembleModel_XT',
  'NeuralNetTorch_r121_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'RandomForest_r16_BAG_L2': 'StackerEnsembleModel_RF',
  'NeuralNetTorch_r135_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'ExtraTrees_r126_BAG_L2': 'StackerEnsembleModel_XT',
  'NeuralNetTorch_r36_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r19_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'XGBoost_r95_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'XGBoost_r34_BAG_L2': 'StackerEnsembleModel_XGBoost',
  'LightGBM_r42_BAG_L2': 'StackerEnsembleModel_LGB',
  'NeuralNetTorch_r1_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'NeuralNetTorch_r89_BAG_L2': 'StackerEnsembleModel_TabularNeuralNetTorch',
  'WeightedEnsemble_L3': 'WeightedEnsembleModel'},
 'model_performance': {'KNeighborsUnif_BAG_L1': 0.95325737657026,
  'KNeighborsDist_BAG_L1': 0.9517966695880806,
  'LightGBMXT_BAG_L1': 0.9585159217061058,
  'LightGBM_BAG_L1': 0.9564709319310546,
  'RandomForestGini_BAG_L1': 0.9547180835524394,
  'RandomForestEntr_BAG_L1': 0.9564709319310546,
  'ExtraTreesGini_BAG_L1': 0.9544259421560035,
  'ExtraTreesEntr_BAG_L1': 0.9544259421560035,
  'XGBoost_BAG_L1': 0.9573473561203623,
  'NeuralNetTorch_BAG_L1': 0.9535495179666958,
  'LightGBMLarge_BAG_L1': 0.9573473561203623,
  'NeuralNetTorch_r79_BAG_L1': 0.9573473561203623,
  'LightGBM_r131_BAG_L1': 0.9558866491381829,
  'LightGBM_r96_BAG_L1': 0.9544259421560035,
  'NeuralNetTorch_r22_BAG_L1': 0.955594507741747,
  'XGBoost_r33_BAG_L1': 0.9570552147239264,
  'ExtraTrees_r42_BAG_L1': 0.9558866491381829,
  'RandomForest_r195_BAG_L1': 0.9517966695880806,
  'LightGBM_r188_BAG_L1': 0.9588080631025416,
  'XGBoost_r89_BAG_L1': 0.9570552147239264,
  'NeuralNetTorch_r30_BAG_L1': 0.9541338007595677,
  'LightGBM_r130_BAG_L1': 0.9570552147239264,
  'NeuralNetTorch_r86_BAG_L1': 0.9547180835524394,
  'XGBoost_r194_BAG_L1': 0.957931638913234,
  'ExtraTrees_r172_BAG_L1': 0.955594507741747,
  'NeuralNetTorch_r14_BAG_L1': 0.9558866491381829,
  'LightGBM_r161_BAG_L1': 0.9550102249488752,
  'LightGBM_r196_BAG_L1': 0.9535495179666958,
  'RandomForest_r39_BAG_L1': 0.9526730937773883,
  'NeuralNetTorch_r41_BAG_L1': 0.9541338007595677,
  'XGBoost_r98_BAG_L1': 0.9535495179666958,
  'LightGBM_r15_BAG_L1': 0.9561787905346187,
  'NeuralNetTorch_r158_BAG_L1': 0.9535495179666958,
  'NeuralNetTorch_r197_BAG_L1': 0.955594507741747,
  'ExtraTrees_r49_BAG_L1': 0.9544259421560035,
  'LightGBM_r143_BAG_L1': 0.9561787905346187,
  'RandomForest_r127_BAG_L1': 0.9538416593631318,
  'RandomForest_r34_BAG_L1': 0.9535495179666958,
  'LightGBM_r94_BAG_L1': 0.9564709319310546,
  'NeuralNetTorch_r143_BAG_L1': 0.9561787905346187,
  'NeuralNetTorch_r31_BAG_L1': 0.9550102249488752,
  'ExtraTrees_r4_BAG_L1': 0.9535495179666958,
  'LightGBM_r30_BAG_L1': 0.9570552147239264,
  'XGBoost_r49_BAG_L1': 0.9564709319310546,
  'NeuralNetTorch_r87_BAG_L1': 0.9535495179666958,
  'NeuralNetTorch_r71_BAG_L1': 0.9553023663453112,
  'ExtraTrees_r178_BAG_L1': 0.955594507741747,
  'RandomForest_r166_BAG_L1': 0.9547180835524394,
  'XGBoost_r31_BAG_L1': 0.9561787905346187,
  'NeuralNetTorch_r185_BAG_L1': 0.9567630733274906,
  'RandomForest_r15_BAG_L1': 0.9544259421560035,
  'LightGBM_r135_BAG_L1': 0.9573473561203623,
  'XGBoost_r22_BAG_L1': 0.9564709319310546,
  'LightGBM_r121_BAG_L1': 0.9547180835524394,
  'NeuralNetTorch_r76_BAG_L1': 0.9573473561203623,
  'ExtraTrees_r197_BAG_L1': 0.955594507741747,
  'NeuralNetTorch_r121_BAG_L1': 0.9535495179666958,
  'RandomForest_r16_BAG_L1': 0.950920245398773,
  'NeuralNetTorch_r135_BAG_L1': 0.9547180835524394,
  'ExtraTrees_r126_BAG_L1': 0.9535495179666958,
  'NeuralNetTorch_r36_BAG_L1': 0.9538416593631318,
  'NeuralNetTorch_r19_BAG_L1': 0.9561787905346187,
  'XGBoost_r95_BAG_L1': 0.9582237803096699,
  'XGBoost_r34_BAG_L1': 0.9558866491381829,
  'LightGBM_r42_BAG_L1': 0.9576394975167981,
  'NeuralNetTorch_r1_BAG_L1': 0.9547180835524394,
  'NeuralNetTorch_r89_BAG_L1': 0.9541338007595677,
  'WeightedEnsemble_L2': 0.9588080631025416,
  'LightGBMXT_BAG_L2': 0.9582237803096699,
  'LightGBM_BAG_L2': 0.9605609114811569,
  'RandomForestGini_BAG_L2': 0.9617294770669004,
  'RandomForestEntr_BAG_L2': 0.9599766286882851,
  'ExtraTreesGini_BAG_L2': 0.9596844872918493,
  'ExtraTreesEntr_BAG_L2': 0.9585159217061058,
  'XGBoost_BAG_L2': 0.9617294770669004,
  'NeuralNetTorch_BAG_L2': 0.9558866491381829,
  'LightGBMLarge_BAG_L2': 0.9614373356704645,
  'NeuralNetTorch_r79_BAG_L2': 0.9573473561203623,
  'LightGBM_r131_BAG_L2': 0.9605609114811569,
  'LightGBM_r96_BAG_L2': 0.9582237803096699,
  'NeuralNetTorch_r22_BAG_L2': 0.9573473561203623,
  'XGBoost_r33_BAG_L2': 0.9588080631025416,
  'ExtraTrees_r42_BAG_L2': 0.9608530528775927,
  'RandomForest_r195_BAG_L2': 0.9605609114811569,
  'LightGBM_r188_BAG_L2': 0.957931638913234,
  'XGBoost_r89_BAG_L2': 0.9605609114811569,
  'NeuralNetTorch_r30_BAG_L2': 0.957931638913234,
  'LightGBM_r130_BAG_L2': 0.9617294770669004,
  'NeuralNetTorch_r86_BAG_L2': 0.9567630733274906,
  'XGBoost_r194_BAG_L2': 0.9608530528775927,
  'ExtraTrees_r172_BAG_L2': 0.9599766286882851,
  'NeuralNetTorch_r14_BAG_L2': 0.9564709319310546,
  'LightGBM_r161_BAG_L2': 0.960268770084721,
  'LightGBM_r196_BAG_L2': 0.9570552147239264,
  'RandomForest_r39_BAG_L2': 0.9605609114811569,
  'NeuralNetTorch_r41_BAG_L2': 0.9558866491381829,
  'XGBoost_r98_BAG_L2': 0.9582237803096699,
  'LightGBM_r15_BAG_L2': 0.9611451942740287,
  'NeuralNetTorch_r158_BAG_L2': 0.9573473561203623,
  'NeuralNetTorch_r197_BAG_L2': 0.9582237803096699,
  'ExtraTrees_r49_BAG_L2': 0.9596844872918493,
  'LightGBM_r143_BAG_L2': 0.9611451942740287,
  'RandomForest_r127_BAG_L2': 0.960268770084721,
  'RandomForest_r34_BAG_L2': 0.9526730937773883,
  'LightGBM_r94_BAG_L2': 0.957931638913234,
  'NeuralNetTorch_r143_BAG_L2': 0.9570552147239264,
  'NeuralNetTorch_r31_BAG_L2': 0.957931638913234,
  'ExtraTrees_r4_BAG_L2': 0.9561787905346187,
  'LightGBM_r30_BAG_L2': 0.9576394975167981,
  'XGBoost_r49_BAG_L2': 0.9593923458954133,
  'NeuralNetTorch_r87_BAG_L2': 0.9553023663453112,
  'NeuralNetTorch_r71_BAG_L2': 0.9573473561203623,
  'ExtraTrees_r178_BAG_L2': 0.960268770084721,
  'RandomForest_r166_BAG_L2': 0.9611451942740287,
  'XGBoost_r31_BAG_L2': 0.9596844872918493,
  'NeuralNetTorch_r185_BAG_L2': 0.957931638913234,
  'RandomForest_r15_BAG_L2': 0.9611451942740287,
  'LightGBM_r135_BAG_L2': 0.9611451942740287,
  'XGBoost_r22_BAG_L2': 0.960268770084721,
  'LightGBM_r121_BAG_L2': 0.9605609114811569,
  'NeuralNetTorch_r76_BAG_L2': 0.9582237803096699,
  'ExtraTrees_r197_BAG_L2': 0.960268770084721,
  'NeuralNetTorch_r121_BAG_L2': 0.9544259421560035,
  'RandomForest_r16_BAG_L2': 0.9614373356704645,
  'NeuralNetTorch_r135_BAG_L2': 0.9593923458954133,
  'ExtraTrees_r126_BAG_L2': 0.9588080631025416,
  'NeuralNetTorch_r36_BAG_L2': 0.9573473561203623,
  'NeuralNetTorch_r19_BAG_L2': 0.9570552147239264,
  'XGBoost_r95_BAG_L2': 0.9620216184633362,
  'XGBoost_r34_BAG_L2': 0.960268770084721,
  'LightGBM_r42_BAG_L2': 0.9573473561203623,
  'NeuralNetTorch_r1_BAG_L2': 0.9585159217061058,
  'NeuralNetTorch_r89_BAG_L2': 0.9561787905346187,
  'WeightedEnsemble_L3': 0.9620216184633362},
 'model_best': 'WeightedEnsemble_L3',
 'model_paths': {'KNeighborsUnif_BAG_L1': ['KNeighborsUnif_BAG_L1'],
  'KNeighborsDist_BAG_L1': ['KNeighborsDist_BAG_L1'],
  'LightGBMXT_BAG_L1': ['LightGBMXT_BAG_L1'],
  'LightGBM_BAG_L1': ['LightGBM_BAG_L1'],
  'RandomForestGini_BAG_L1': ['RandomForestGini_BAG_L1'],
  'RandomForestEntr_BAG_L1': ['RandomForestEntr_BAG_L1'],
  'ExtraTreesGini_BAG_L1': ['ExtraTreesGini_BAG_L1'],
  'ExtraTreesEntr_BAG_L1': ['ExtraTreesEntr_BAG_L1'],
  'XGBoost_BAG_L1': ['XGBoost_BAG_L1'],
  'NeuralNetTorch_BAG_L1': ['NeuralNetTorch_BAG_L1'],
  'LightGBMLarge_BAG_L1': ['LightGBMLarge_BAG_L1'],
  'NeuralNetTorch_r79_BAG_L1': ['NeuralNetTorch_r79_BAG_L1'],
  'LightGBM_r131_BAG_L1': ['LightGBM_r131_BAG_L1'],
  'LightGBM_r96_BAG_L1': ['LightGBM_r96_BAG_L1'],
  'NeuralNetTorch_r22_BAG_L1': ['NeuralNetTorch_r22_BAG_L1'],
  'XGBoost_r33_BAG_L1': ['XGBoost_r33_BAG_L1'],
  'ExtraTrees_r42_BAG_L1': ['ExtraTrees_r42_BAG_L1'],
  'RandomForest_r195_BAG_L1': ['RandomForest_r195_BAG_L1'],
  'LightGBM_r188_BAG_L1': ['LightGBM_r188_BAG_L1'],
  'XGBoost_r89_BAG_L1': ['XGBoost_r89_BAG_L1'],
  'NeuralNetTorch_r30_BAG_L1': ['NeuralNetTorch_r30_BAG_L1'],
  'LightGBM_r130_BAG_L1': ['LightGBM_r130_BAG_L1'],
  'NeuralNetTorch_r86_BAG_L1': ['NeuralNetTorch_r86_BAG_L1'],
  'XGBoost_r194_BAG_L1': ['XGBoost_r194_BAG_L1'],
  'ExtraTrees_r172_BAG_L1': ['ExtraTrees_r172_BAG_L1'],
  'NeuralNetTorch_r14_BAG_L1': ['NeuralNetTorch_r14_BAG_L1'],
  'LightGBM_r161_BAG_L1': ['LightGBM_r161_BAG_L1'],
  'LightGBM_r196_BAG_L1': ['LightGBM_r196_BAG_L1'],
  'RandomForest_r39_BAG_L1': ['RandomForest_r39_BAG_L1'],
  'NeuralNetTorch_r41_BAG_L1': ['NeuralNetTorch_r41_BAG_L1'],
  'XGBoost_r98_BAG_L1': ['XGBoost_r98_BAG_L1'],
  'LightGBM_r15_BAG_L1': ['LightGBM_r15_BAG_L1'],
  'NeuralNetTorch_r158_BAG_L1': ['NeuralNetTorch_r158_BAG_L1'],
  'NeuralNetTorch_r197_BAG_L1': ['NeuralNetTorch_r197_BAG_L1'],
  'ExtraTrees_r49_BAG_L1': ['ExtraTrees_r49_BAG_L1'],
  'LightGBM_r143_BAG_L1': ['LightGBM_r143_BAG_L1'],
  'RandomForest_r127_BAG_L1': ['RandomForest_r127_BAG_L1'],
  'RandomForest_r34_BAG_L1': ['RandomForest_r34_BAG_L1'],
  'LightGBM_r94_BAG_L1': ['LightGBM_r94_BAG_L1'],
  'NeuralNetTorch_r143_BAG_L1': ['NeuralNetTorch_r143_BAG_L1'],
  'NeuralNetTorch_r31_BAG_L1': ['NeuralNetTorch_r31_BAG_L1'],
  'ExtraTrees_r4_BAG_L1': ['ExtraTrees_r4_BAG_L1'],
  'LightGBM_r30_BAG_L1': ['LightGBM_r30_BAG_L1'],
  'XGBoost_r49_BAG_L1': ['XGBoost_r49_BAG_L1'],
  'NeuralNetTorch_r87_BAG_L1': ['NeuralNetTorch_r87_BAG_L1'],
  'NeuralNetTorch_r71_BAG_L1': ['NeuralNetTorch_r71_BAG_L1'],
  'ExtraTrees_r178_BAG_L1': ['ExtraTrees_r178_BAG_L1'],
  'RandomForest_r166_BAG_L1': ['RandomForest_r166_BAG_L1'],
  'XGBoost_r31_BAG_L1': ['XGBoost_r31_BAG_L1'],
  'NeuralNetTorch_r185_BAG_L1': ['NeuralNetTorch_r185_BAG_L1'],
  'RandomForest_r15_BAG_L1': ['RandomForest_r15_BAG_L1'],
  'LightGBM_r135_BAG_L1': ['LightGBM_r135_BAG_L1'],
  'XGBoost_r22_BAG_L1': ['XGBoost_r22_BAG_L1'],
  'LightGBM_r121_BAG_L1': ['LightGBM_r121_BAG_L1'],
  'NeuralNetTorch_r76_BAG_L1': ['NeuralNetTorch_r76_BAG_L1'],
  'ExtraTrees_r197_BAG_L1': ['ExtraTrees_r197_BAG_L1'],
  'NeuralNetTorch_r121_BAG_L1': ['NeuralNetTorch_r121_BAG_L1'],
  'RandomForest_r16_BAG_L1': ['RandomForest_r16_BAG_L1'],
  'NeuralNetTorch_r135_BAG_L1': ['NeuralNetTorch_r135_BAG_L1'],
  'ExtraTrees_r126_BAG_L1': ['ExtraTrees_r126_BAG_L1'],
  'NeuralNetTorch_r36_BAG_L1': ['NeuralNetTorch_r36_BAG_L1'],
  'NeuralNetTorch_r19_BAG_L1': ['NeuralNetTorch_r19_BAG_L1'],
  'XGBoost_r95_BAG_L1': ['XGBoost_r95_BAG_L1'],
  'XGBoost_r34_BAG_L1': ['XGBoost_r34_BAG_L1'],
  'LightGBM_r42_BAG_L1': ['LightGBM_r42_BAG_L1'],
  'NeuralNetTorch_r1_BAG_L1': ['NeuralNetTorch_r1_BAG_L1'],
  'NeuralNetTorch_r89_BAG_L1': ['NeuralNetTorch_r89_BAG_L1'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2'],
  'LightGBMXT_BAG_L2': ['LightGBMXT_BAG_L2'],
  'LightGBM_BAG_L2': ['LightGBM_BAG_L2'],
  'RandomForestGini_BAG_L2': ['RandomForestGini_BAG_L2'],
  'RandomForestEntr_BAG_L2': ['RandomForestEntr_BAG_L2'],
  'ExtraTreesGini_BAG_L2': ['ExtraTreesGini_BAG_L2'],
  'ExtraTreesEntr_BAG_L2': ['ExtraTreesEntr_BAG_L2'],
  'XGBoost_BAG_L2': ['XGBoost_BAG_L2'],
  'NeuralNetTorch_BAG_L2': ['NeuralNetTorch_BAG_L2'],
  'LightGBMLarge_BAG_L2': ['LightGBMLarge_BAG_L2'],
  'NeuralNetTorch_r79_BAG_L2': ['NeuralNetTorch_r79_BAG_L2'],
  'LightGBM_r131_BAG_L2': ['LightGBM_r131_BAG_L2'],
  'LightGBM_r96_BAG_L2': ['LightGBM_r96_BAG_L2'],
  'NeuralNetTorch_r22_BAG_L2': ['NeuralNetTorch_r22_BAG_L2'],
  'XGBoost_r33_BAG_L2': ['XGBoost_r33_BAG_L2'],
  'ExtraTrees_r42_BAG_L2': ['ExtraTrees_r42_BAG_L2'],
  'RandomForest_r195_BAG_L2': ['RandomForest_r195_BAG_L2'],
  'LightGBM_r188_BAG_L2': ['LightGBM_r188_BAG_L2'],
  'XGBoost_r89_BAG_L2': ['XGBoost_r89_BAG_L2'],
  'NeuralNetTorch_r30_BAG_L2': ['NeuralNetTorch_r30_BAG_L2'],
  'LightGBM_r130_BAG_L2': ['LightGBM_r130_BAG_L2'],
  'NeuralNetTorch_r86_BAG_L2': ['NeuralNetTorch_r86_BAG_L2'],
  'XGBoost_r194_BAG_L2': ['XGBoost_r194_BAG_L2'],
  'ExtraTrees_r172_BAG_L2': ['ExtraTrees_r172_BAG_L2'],
  'NeuralNetTorch_r14_BAG_L2': ['NeuralNetTorch_r14_BAG_L2'],
  'LightGBM_r161_BAG_L2': ['LightGBM_r161_BAG_L2'],
  'LightGBM_r196_BAG_L2': ['LightGBM_r196_BAG_L2'],
  'RandomForest_r39_BAG_L2': ['RandomForest_r39_BAG_L2'],
  'NeuralNetTorch_r41_BAG_L2': ['NeuralNetTorch_r41_BAG_L2'],

In [ ]:
predictor.leaderboard(df_train, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,KNeighborsDist_BAG_L1,1.00000,0.951797,accuracy,0.015249,0.013795,0.001738,0.015249,0.013795,0.001738,1,True,2
1,RandomForest_r195_BAG_L1,1.00000,0.951797,accuracy,0.032763,0.074908,0.455394,0.032763,0.074908,0.455394,1,True,18
2,RandomForest_r166_BAG_L1,1.00000,0.954718,accuracy,0.032846,0.068886,0.329878,0.032846,0.068886,0.329878,1,True,48
3,RandomForest_r16_BAG_L1,1.00000,0.950920,accuracy,0.033249,0.070461,0.517570,0.033249,0.070461,0.517570,1,True,58
4,RandomForestEntr_BAG_L1,1.00000,0.956471,accuracy,0.033487,0.071497,0.274678,0.033487,0.071497,0.274678,1,True,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,LightGBM_r30_BAG_L2,0.95355,0.957639,accuracy,4.479624,3.285554,143.014854,0.119820,0.080483,2.677157,2,True,109
130,LightGBM_r196_BAG_L2,0.95355,0.957055,accuracy,4.507765,3.311170,144.321765,0.147961,0.106098,3.984068,2,True,94
131,NeuralNetTorch_BAG_L2,0.95355,0.955887,accuracy,4.709995,3.390340,146.950538,0.350191,0.185268,6.612841,2,True,76
132,NeuralNetTorch_r87_BAG_L2,0.95355,0.955302,accuracy,4.719317,3.381824,147.029887,0.359513,0.176753,6.692190,2,True,111
133,NeuralNetTorch_r121_BAG_L2,0.95355,0.954426,accuracy,4.739106,3.409735,149.438016,0.379302,0.204664,9.100319,2,True,123

In [ ]:
predictor.feature_importance(data=df_train)

Computing feature importance via permutation shuffling for 11 features using 3423 rows with 5 shuffle sets...
	258.08s	= Expected runtime (51.62s per shuffle set)
	137.32s	= Actual runtime (Completed 5 of 5 shuffle sets)

                   importance    stddev   p_value  n  p99_high   p99_low
bmi                  0.013088  0.001139  0.000007  5  0.015433  0.010743
age                  0.011160  0.001361  0.000026  5  0.013962  0.008358
ever_married         0.005843  0.000547  0.000009  5  0.006968  0.004717
heart_disease        0.005083  0.000867  0.000098  5  0.006868  0.003299
id                   0.004908  0.000697  0.000048  5  0.006344  0.003472
avg_glucose_level    0.004499  0.000443  0.000011  5  0.005411  0.003587
hypertension         0.004148  0.000381  0.000008  5  0.004933  0.003364
gender               0.003856  0.000562  0.000053  5  0.005013  0.002699
smoking_status       0.003214  0.000584  0.000126  5  0.004417  0.002011
Residence_type       0.002863  0.000244  0.000006  5  0.003366  0.002360
work_type            0.002805  0.000569  0.000193  5  0.003977  0.001632

In [ ]:
y_pred = predictor.predict(test_data)
y_pred=pd.DataFrame(y_pred,columns=['label'])
y_pred

      stroke
4673       0
3232       0
3694       0
1070       0
4163       0
...      ...
386        0
3961       0
1608       0
1459       0
4058       0

[1687 rows x 1 columns]

In [ ]:
predictor.evaluate(df_test)

{'accuracy': 0.941908713692946,
 'balanced_accuracy': 0.5079802407291449,
 'mcc': 0.04267973085827943,
 'roc_auc': 0.8320601127113338,
 'f1': 0.0392156862745098,
 'precision': 0.16666666666666666,
 'recall': 0.022222222222222223}

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

# Assuming you have your actual labels and predictions in these variables
# Replace these with your actual variables
# y_test = actual class labels
# y_pred = predicted class labels

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Create a prettier visualization
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(10, 8))
disp.plot(cmap=plt.cm.Blues, ax=ax)
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

# Additionally, print classification report for metrics
print(classification_report(y_test, y_pred))

In [ ]:
# Calculate MAPE and accuracy
mape = (abs(df_test['quantity'] - predictions) / df_test['quantity']).mean() * 100
accuracy = 100 - mape

print(f"MAPE: {mape:.2f}%")
print(f"Estimated Accuracy: {accuracy:.2f}%")